import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Header from "../components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!dark">
      <body className={inter.className}>
        <Header />
        <div className="flex h-full flex-col gap-4 mt-4 container mx-auto">
          <div className="flex-1">{children}</div>
        </div>

        <Toaster />
      </body>
    </html>
  );
}
